name: Lint-On-Pull

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  issues: write

jobs:
  lint-on-pull:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Super-Linter
        id: super-linter
        uses: super-linter/super-linter@v7.1.0
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Append summary to issue file
        if: failure()
        run: cat super-linter-output/super-linter-summary.md >> .github/issue-templates/lint-failed-on-pull.md

      - name: Get shortened commit SHA
        if: failure()
        run: |
          SHORT_SHA=$(echo "${{ github.event.pull_request.head.sha }}" | cut -c1-7)
          echo "SHORT_SHA=$SHORT_SHA" >> "$GITHUB_ENV"

      - name: Create Issue If Lint Failed
        if: failure()
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_SHA: ${{ env.SHORT_SHA }}
          PULL_AUTHOR: ${{ github.event.pull_request.user.login }}
          PULL_TITLE: ${{ github.event.pull_request.title }}
        with:
          filename: .github/issue-templates/lint-failed-on-pull.md
