name: Lint-On-Push

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write

jobs:
  lint-on-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Super-Linter
        id: super-linter
        uses: super-linter/super-linter@v7.1.0
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SAVE_SUPER_LINTER_SUMMARY: true

      - name: Append summary to issue file
        if: failure()
        run: cat super-linter-output/super-linter-summary.md >> .github/issue-templates/lint-failed-on-push.md

      - name: Get shortened commit SHA
        if: failure()
        env:
          AUTHOR: ${{ github.event.head_commit.author.name }}
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
            echo "SHORT_SHA=$SHORT_SHA" >> "$GITHUB_ENV"
          echo "${{ env.AUTHOR }}"

      - name: Create Issue If Lint Failed
        if: failure()
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_SHA: ${{ env.SHORT_SHA }}
          COMMIT_NAME: ${{ github.event.head_commit.message }}
          COMMIT_AUTHOR: ${{ github.event.head_commit.author.name }}
          LINT_SUMMARY: ${{ env.FILE_CONTENT }}
        with:
          filename: .github/issue-templates/lint-failed-on-push.md
